### ISSUE TITLE
[android] Using --livereload with ionic renders error 

### ISSUE THREAD

**Issue by maxpaj** [auth0/auth0-cordova#78]
I've noticed that when I run the app on my device with `--livereload` I'm getting this:

```
Error: Uncaught (in promise): TypeError: Cannot read property 'isAvailable' of undefined
TypeError: Cannot read property 'isAvailable' of undefined
    at Function.Browser.isAvailable (http://192.168.43.232:8100/build/vendor.js:194714:31)
    at getAgent (http://192.168.43.232:8100/build/vendor.js:194693:23)
    at CordovaAuth.authorize (http://192.168.43.232:8100/build/vendor.js:110120:3)
    at http://192.168.43.232:8100/build/main.js:726:20
    at new t (http://192.168.43.232:8100/build/polyfills.js:3:21506)
    at AuthService.webpackJsonp.42.AuthService.login (http://192.168.43.232:8100/build/main.js:720:16)
    at IntroPage.webpackJsonp.465.IntroPage.login (http://192.168.43.232:8100/build/main.js:1544:19)
    at Object.eval [as handleEvent] (ng:///AppModule/IntroPage.ngfactory.js:68:31)
    at Object.handleEvent (http://192.168.43.232:8100/build/vendor.js:13912:155)
    at Object.handleEvent (http://192.168.43.232:8100/build/vendor.js:14644:29)
  at Function.Browser.isAvailable (/vendor.js:194714:31)
  at getAgent (/vendor.js:194693:23)
  at CordovaAuth.authorize (/vendor.js:110120:3)
  at None (/main.js:726:20)
  at new t (/polyfills.js:3:21506)
...
(14 additional frame(s) were not displayed)
```

Here's a snippet of my config.xml:

```
    <plugin name="cordova-plugin-safariviewcontroller" spec="^1.5.2" />
    <plugin name="cordova-plugin-inappbrowser" spec="^2.0.1" />
    <plugin name="cordova-plugin-customurlscheme" spec="~4.3.0">
        <variable name="URL_SCHEME" value="*masked*.app.mobile" />
        <variable name="ANDROID_SCHEME" value="*masked*.app.mobile" />
        <variable name="ANDROID_HOST" value="*masked*.auth0.com" />
        <variable name="ANDROID_PATHPREFIX" value="/cordova/*masked*.app.mobile/callback" />
    </plugin>
```

Device: Samsung Galaxy S8

It would help immensely if I'd be able to develop with `--livereload` on my device.

**Comment by maxpaj** [comment]
This had nothing to do with this plugin.

**Comment by tareqdayya** [comment]
@maxpaj What was causing it? i'm running into same issue.

**Comment by kettunen** [comment]
This happens when upgraded Ionic application from Angular 8 to 9, 10, or 11. @maxpaj what did you do to fix this?
